// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalRealTime.Data;

#nullable disable

namespace PortalRealTime.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240723051230_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalRealTime.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "OPD อายุรกรรม"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "OPD ศัลยกรรม"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "ห้องเจาะเลือด"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "ห้อง x-ray"
                        });
                });

            modelBuilder.Entity("PortalRealTime.Models.JobStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JobStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobStatusName = "ร้องขอ"
                        },
                        new
                        {
                            Id = 2,
                            JobStatusName = "จ่ายงาน"
                        },
                        new
                        {
                            Id = 3,
                            JobStatusName = "กำลังเดินทาง"
                        },
                        new
                        {
                            Id = 4,
                            JobStatusName = "การบริการเสร็จสิ้น"
                        });
                });

            modelBuilder.Entity("PortalRealTime.Models.NurseRequest", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndPointId")
                        .HasColumnType("int");

                    b.Property<string>("Hn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PortalCarTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PortalNameId")
                        .HasColumnType("int");

                    b.Property<int>("RemarkId")
                        .HasColumnType("int");

                    b.Property<int>("StartPointId")
                        .HasColumnType("int");

                    b.Property<int>("UrgencyTypeId")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("EndPointId");

                    b.HasIndex("JobStatusId");

                    b.HasIndex("PortalCarTypeId");

                    b.HasIndex("PortalNameId");

                    b.HasIndex("RemarkId");

                    b.HasIndex("StartPointId");

                    b.HasIndex("UrgencyTypeId");

                    b.ToTable("NurseRequest");
                });

            modelBuilder.Entity("PortalRealTime.Models.PortalCarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PortalCarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortalCarType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PortalCarName = "รถนั่ง"
                        },
                        new
                        {
                            Id = 2,
                            PortalCarName = "รถนอน"
                        });
                });

            modelBuilder.Entity("PortalRealTime.Models.PortalClerk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PortalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortalClerk");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PortalName = "รณรงค์ มาลามาศ"
                        },
                        new
                        {
                            Id = 2,
                            PortalName = "กิตติ ภูมิบูรณ์"
                        });
                });

            modelBuilder.Entity("PortalRealTime.Models.Remark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RemarkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Remark");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RemarkName = "ผู้ป่วยติดเชื้อ"
                        },
                        new
                        {
                            Id = 2,
                            RemarkName = "ผู้ป่วยอ้วน ขอเวรเปล 2 คน"
                        });
                });

            modelBuilder.Entity("PortalRealTime.Models.UrgencyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UrgencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UrgencyType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UrgencyName = "ปกติ"
                        },
                        new
                        {
                            Id = 2,
                            UrgencyName = "ด่วน"
                        },
                        new
                        {
                            Id = 3,
                            UrgencyName = "ด่วนมาก"
                        });
                });

            modelBuilder.Entity("PortalRealTime.Models.NurseRequest", b =>
                {
                    b.HasOne("PortalRealTime.Models.Department", "EndDepartment")
                        .WithMany()
                        .HasForeignKey("EndPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalRealTime.Models.JobStatus", "JobStatus")
                        .WithMany()
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalRealTime.Models.PortalCarType", "PortalCarType")
                        .WithMany()
                        .HasForeignKey("PortalCarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalRealTime.Models.PortalClerk", "PortalName")
                        .WithMany()
                        .HasForeignKey("PortalNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalRealTime.Models.Remark", "Remark")
                        .WithMany()
                        .HasForeignKey("RemarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalRealTime.Models.Department", "StartDepartment")
                        .WithMany()
                        .HasForeignKey("StartPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalRealTime.Models.UrgencyType", "UrgencyType")
                        .WithMany()
                        .HasForeignKey("UrgencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndDepartment");

                    b.Navigation("JobStatus");

                    b.Navigation("PortalCarType");

                    b.Navigation("PortalName");

                    b.Navigation("Remark");

                    b.Navigation("StartDepartment");

                    b.Navigation("UrgencyType");
                });
#pragma warning restore 612, 618
        }
    }
}
